### ISSUE TITLE
docs: use github pages instead of readthedocs

### ISSUE THREAD

**Issue by smartcmd** [AllayMC/Allay#259]

**Comment by Cdm2883** [comment]
#### `.github/workflows/gh-pages.yml`

```yml
name: Publish docs via GitHub Pages

on:
  push:
    branches: [ "master" ]
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy Docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
```
